version: '3.5'

services:
  postgres:
    container_name: postgres-db
    image: postgres
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: root123
      - POSTGRES_DB: defaultdb
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
